version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  aws-cli: circleci/aws-cli@3.1

jobs:
  aws-cli-setup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
  terraform-run:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .

workflows:  
  deploy_infrastructure:
    jobs:
      - aws-cli-setup:
          context: AWS
      - terraform-run:
          context: AWS
