version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  aws-cli: circleci/aws-cli@3.1

jobs:
  aws-cli-setup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME

workflows:  
  deploy_infrastructure:
    jobs:
      - aws-cli-setup
      - terraform/fmt:
          checkout: true
      - terraform/validate:
          checkout: true
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          requires:
            - terraform/validate
      - terraform/apply:
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
