version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  aws-cli: circleci/aws-cli@3.1

jobs:
  aws-cli-setup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
  terraform-run:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.1.6
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .
      - terraform/init:
          backend: true
          backend_config_file: "elopage/terraform.tfstate"
          path: .
      - terraform/plan:
          backend_config_file: "elopage/terraform.tfstate"
          path: .
      - terraform/apply:
          backend_config_file: "elopage/terraform.tfstate"
          path: .

workflows:  
  deploy_infrastructure:
    jobs:
      - aws-cli-setup:
          context: AWS
      - terraform-run:
          context: AWS
          requires:
            - aws-cli-setup